mysite/urls.py
from django.conf import settings
from django.conf.urls import handler404
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pickem.urls'))
]

handler404 = 'pickem.views.error_404_view'

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pickem/urls.py
from django.urls import path

from . import views

app_name = 'pickem'
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('signup/confirm', views.signupaction, name="signupaction"),
    path('login/', views.loginview, name='loginview'),
    path('login/confirm', views.loginaction, name="loginaction"),
    path('logout/', views.logoutaction, name="logoutaction"),
    path('makepredictions/', views.makepredictions, name="makepredictions"),
    path('adminaction/', views.adminaction, name="adminaction"),
    path('leaderboard/', views.leaderboard, name="leaderboard"),
    path('<str:username>/history/', views.userhistory, name="userhistory"),
    path('importschedule', views.import_schedule, name="import_schedule"),
    path('pastweeks/', views.pastweeks, name="pastweeks"),
    path('addteams/', views.add_teams, name="add_teams")
]

pickem/models.py
from django.contrib.auth.models import User
from django.db import models

class Team(models.Model):
    team_name = models.CharField(max_length=50)
    team_logo = models.CharField(max_length=100)
    team_wins = models.IntegerField(default=0)
    team_losses = models.IntegerField(default=0)

    def __str__(self):
        return self.team_name

    def print_win_loss(self):
        return self.team_wins + "-" + self.team_losses

class Game(models.Model):
    week = models.IntegerField(default=0)
    game_number = models.IntegerField(default=0)
    date_time = models.DateField()
    teams = models.ManyToManyField(Team, related_name='teams')

    has_occurred = models.BooleanField(default=False)
    winning_team = models.ForeignKey(Team, default=None, on_delete=models.CASCADE, blank=True, null=True, related_name='winning_team')

    game_id = models.CharField(max_length=50, default='w0g0')

    def save(self, *args, **kwargs):
        self.game_id = "w"+str(self.week)+"g"+str(self.game_number)
        super(Game, self).save(*args, **kwargs)

    def __str__(self):
        if self.teams.exists():
            return ' vs. '.join([a.team_name for a in self.teams.all()])
        else:
            return "Week "+str(self.week)+", "+" Game "+str(self.game_number)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    points = models.IntegerField(default=0)
    rank = models.IntegerField(default=0)
    latest_pred_week = models.IntegerField(default=0)
    twitter = models.CharField(max_length=50, blank=True, null=True)
    favorite_team = models.ForeignKey(Team, blank=True, null=True, on_delete=models.CASCADE)
    email_updates = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Prediction(models.Model):
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)
    predicted_team = models.ForeignKey(Team, blank=True, null=True, on_delete=models.CASCADE)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return self.user_profile.user.username + " - " + self.game.game_id
    

pickem/views.py
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from .models import Team, Game, UserProfile, Prediction

import csv
import json
import os
from datetime import datetime

current_week = settings.CURRENT_WEEK
week_start = False
if settings.WEEK_START == 1:
    week_start = True

def error_404_view(request, exception):
    context = {

    }
    return render(request,'pickem/404.html', context)

def index(request):
    current_week_games = Game.objects.filter(week=current_week).order_by('game_number')

    games_dict = {}
    game_ids = []

    curr_date = ""
    for game in current_week_games:
        game_ids.append(game.game_id)
        game_date = game.date_time.strftime("%A %B %d")
        if game_date != curr_date:
            curr_date = game_date
            games_dict[curr_date] = []
        games_dict[curr_date].append(game)
    games_dict = sorted(games_dict.items())
    
    request.session['games'] = json.dumps(game_ids)
    request.session['week'] = current_week
    request.session['current_page'] = 'home'

    if request.user.is_authenticated:
        user = request.user
        user_profile = UserProfile.objects.get(user=user)
        user_predictions = user_profile.prediction_set.filter(game__week=current_week).order_by('game__game_number')

        user_preds_dict = {}
        curr_date = ""
        for prediction in user_predictions:
            game_date = prediction.game.date_time.strftime("%A %B %d")
            if game_date != curr_date:
                curr_date = game_date
                user_preds_dict[curr_date] = []
            user_preds_dict[curr_date].append(prediction)
        user_preds_dict = sorted(user_preds_dict.items())
    else:
        user_profile = None
        user_preds_dict = None

    if 'User-Agent' in request.headers:
        if "iPhone" in request.headers['User-Agent'] or "Android" in request.headers['User-Agent']:
            agent = "mobile"
        else:
            agent = "web"
    else:
        agent = None

    login_message = request.session.get('login_message')
    if login_message:
        request.session['login_message'] = False

    prediction_message = request.session.get('prediction_message')
    if prediction_message:
        request.session['prediction_message'] = False

    context = {
        'current_week' : current_week,
        'current_week_games': games_dict,
        'user_profile': user_profile,
        'user_predictions': user_preds_dict,
        'week_start': week_start,
        'login_message': login_message,
        'prediction_message': prediction_message,
        'agent': agent
    }
    return render(request, 'pickem/index.html', context)

def leaderboard(request):
    request.session['current_page'] = 'leaderboard'
    
    users = UserProfile.objects.all().order_by('-points')
    users = users.exclude(user__username='admin')

    if request.user.is_authenticated:
        user = request.user
        user_profile = UserProfile.objects.get(user=user)
    else:
        user_profile = None

    if 'User-Agent' in request.headers:
        if "iPhone" in request.headers['User-Agent'] or "Android" in request.headers['User-Agent']:
            agent = "mobile"
        else:
            agent = "web"
    else:
        agent = None
    
    context = {
        'users': users,
        'user_profile': user_profile,
        'agent': agent,
    }

    return render(request, 'pickem/leaderboard.html', context)

def userhistory(request, username):
    request.session['current_page'] = 'history'

    request.session['week'] = current_week

    user = UserProfile.objects.get(user__username=username)
    user_week = user.latest_pred_week

    pred_list = []

    for i in range(1, user_week+1):
        week = user.prediction_set.filter(game__week=i).order_by('game__game_number')
        pred_list.append(week)

    if request.user.is_authenticated:
        auth_user = request.user
        user_profile = UserProfile.objects.get(user=auth_user)
    else:
        user_profile = None

    context = {
        'profile': user,
        'user_predictions': pred_list,
        'user_profile': user_profile
    }

    return render(request, 'pickem/userhistory.html', context)

def pastweeks(request):
    request.session['current_page'] = 'pastweeks'
    request.session['week'] = current_week

    if current_week == 1:
        week_list = None
    else:
        week_list = []
        for i in range(1, current_week):
            week_list.append(Game.objects.filter(week=i).order_by('game_number'))
    
    if request.user.is_authenticated:
        user = request.user
        user_profile = UserProfile.objects.get(user=user)
    else:
        user_profile = None
    
    if 'User-Agent' in request.headers:
        if "iPhone" in request.headers['User-Agent'] or "Android" in request.headers['User-Agent']:
            agent = "mobile"
        else:
            agent = "web"
    else:
        agent = None

    context = {
        'week_list': week_list,
        'last_week': current_week-1,
        'user_profile': user_profile,
        'agent': agent,
    }

    return render(request, 'pickem/pastweeks.html', context)


def signup(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('pickem:index', args=()))
    else:
        request.session['current_page'] = 'signup'

        context = {
            'teams': Team.objects.all().order_by('team_name')
        }
        return render(request, 'pickem/signup.html', context)

def signupaction(request):
    try:
        print(request.POST)
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        confirm_password = request.POST['confirmpassword']
        twitter = request.POST['twitter']
        team_name = request.POST['team']
        if team_name == "No Favorite Team":
            team = None
        else:
            team = Team.objects.get(team_name=team_name)
        if "emailupdates" in request.POST:
            email_updates = True
        else:
            email_updates = False
    except KeyError:
        return render(request, 'pickem/signup.html', {'error_message': "Not all required fields were provided.", 'teams': Team.objects.all().order_by('team_name')})
    else:
        if User.objects.filter(username=username).exists():
            return render(request, 'pickem/signup.html', {'error_message': "That username already exists!", 'teams': Team.objects.all().order_by('team_name')})
        if User.objects.filter(email=email).exists():
            return render(request, 'pickem/signup.html', {'error_message': "That email already exists!", 'teams': Team.objects.all().order_by('team_name')})
        if not username.isalnum():
            return render(request, 'pickem/signup.html', {'error_message': "Username cannot contain special characters!", 'teams': Team.objects.all().order_by('team_name')})
        if password != confirm_password:
            return render(request, 'pickem/signup.html', {'error_message': "Passwords do not match!", 'teams': Team.objects.all().order_by('team_name')})
        else:
            user = User.objects.create_user(username=username, password=password, email=email)
            new_user = UserProfile(user=user, twitter=twitter, favorite_team=team, email_updates=email_updates)
            new_user.save()
            return loginaction(request)

def loginview(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('pickem:index', args=()))
    else:
        request.session['current_page'] = 'login'
        return render(request, 'pickem/login.html', {})

def loginaction(request):
    try:
        username = request.POST['username']
        password = request.POST['password']
    except KeyError:
        return render(request, 'pickem/login.html', {'error_message': "Not all required fields were provided."})
    else:
        if not username.isalnum():
            if '@' in username:
                try:
                    validate_email(username)
                except ValidationError:
                    return render(request, 'pickem/login.html', {'error_message': "Username cannot contain special characters!"})
                else:
                    users = User.objects.filter(email=username)
                    if len(users) > 0:
                        u = users[0]
                        user = authenticate(request, username=u.username, password=password)
                        if user is not None:
                            login(request, user)
                            request.session['login_message'] = True
                            return HttpResponseRedirect(reverse('pickem:index', args=()))
                        else:
                            return render(request, 'pickem/login.html', {'error_message': "That user does not exist!"})
                    else:
                        return render(request, 'pickem/login.html', {'error_message': "That email has not been registered!"})
        else:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                request.session['login_message'] = True
                return HttpResponseRedirect(reverse('pickem:index', args=()))
            else:
                return render(request, 'pickem/login.html', {'error_message': "That user does not exist!"})

def logoutaction(request):
    logout(request)
    return HttpResponseRedirect(reverse('pickem:index', args=()))


def makepredictions(request):

pickem/templates/pickem/adminform.html
<h3 class="text-center mb-3">Admin View</h1><br>

<form action="{% url 'pickem:adminaction' %}" id="predictions" method="post">
    {% csrf_token %}

    {% if user_profile %}
    <div class="row-md-3 text-center justify-content-center ">
        <button type="submit" class="btn btn-warning btn-lg" value="makepredictions">Lock in!</button>
    </div>
    {% else %}
    <div class="row-md-3 text-center justify-content-center ">
        <p>Login before making predictions!</p>
    </div>
    {% endif %}
    <br>

    {% for day, games in current_week_games %}
    <div>
        <div class="row d-flex flex-wrap align-items-center justify-content-center py-2">
            <h4>{{ day }}</h4>
        </div>
        {% for game in games %}
        <div class="row d-flex flex-nowrap align-items-center justify-content-center py-2">
            {% for team in game.teams.all %}
            <div class="btn-group btn-group-toggle align-items-center justify-content-center" style="width:27.5%;">
                {% if game.has_occurred %}
                <input type="radio" class="btn-check" name="{{ game.game_id }}"
                    value="{{ game.game_id }}-{{ team.team_name }}" id="{{ game.game_id }}-{{ team.team_name }}"
                    autocomplete="off" disabled>
                {% else %}
                <input type="radio" class="btn-check" name="{{ game.game_id }}"
                    value="{{ game.game_id }}-{{ team.team_name }}" id="{{ game.game_id }}-{{ team.team_name }}"
                    autocomplete="off" {% if not user_profile %}disabled{% endif %}>
                {% endif %}
    
                <label
                    class="btn {% if game.has_occurred and team.team_name == game.winning_team.team_name %} btn-outline-success {% else %} {% if game.has_occurred %} btn-outline-danger {% else %} btn-outline-dark {% endif %} {% endif %}"
                    for="{{ game.game_id }}-{{ team.team_name }}">
                    {% if forloop.counter == 1 %}
                    <span>{% if agent and agent == "web" %}{{ team.team_name }} {% endif %}<img src="{{ team.team_logo }}"
                    alt="{{ team.team_name }}" height="45"></span>
                    {% else %}
                    <span><img src="{{ team.team_logo }}" alt="{{ team.team_name }}" height="45">{% if agent and agent == "web" %} {{ team.team_name }}{% endif %}</span>
                    {% endif %}
                </label>
            </div>
            {% if forloop.counter == 1 %}
            <div style="width:10%">
                <p>vs.</p>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <br>
        {% endfor %}
    </div>
    {% endfor %}

    {% if user_profile %}
    <div class="row-md-3 text-center justify-content-center ">
        <button type="submit" class="btn btn-warning btn-lg" value="makepredictions">Lock in!</button>
    </div>
    {% else %}
    <div class="row-md-3 text-center justify-content-center ">
        <p>Login before making predictions!</p>
    </div>
    {% endif %}

</form>

pickem/templates/pickem/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'pickem/style.css' %}">

    <title>OWL Pick'em</title>
</head>

<body>
    {% include 'pickem/navbar.html' %}

    <div class="container-fluid positive-relative" id="main-content" style="text-align: center;">
        {% block content %}
        {% endblock %}
    </div>

    <br><br>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
        crossorigin="anonymous"></script>

</body>

</html>

pickem/templates/pickem/indexform.html
<form action="{% url 'pickem:makepredictions' %}" id="predictions" method="post">
    {% csrf_token %}
    
    {% if user_profile %}
    <div class="row-md-3 text-center justify-content-center ">
        {% if user_profile.latest_pred_week == current_week or week_start %}
        <button type="submit" class="btn btn-outline-dark btn-lg" value="makepredictions" disabled>Locked in!</button>
        {% else %}
        <button type="submit" class="btn btn-warning btn-lg" value="makepredictions">Lock in!</button>
        {% endif %}
    </div>
    {% else %}
    <div class="row-md-3 text-center justify-content-center ">
        <p>Login before making predictions!</p>
    </div>
    {% endif %}
    <br>

    {% for day, games in current_week_games %}
    <div>
        <div class="row d-flex flex-wrap align-items-center justify-content-center py-2">
            <h4>{{ day }}</h4>
        </div>
        {% for game in games %}
        <div class="row d-flex flex-nowrap align-items-center justify-content-center py-2">
            {% for team in game.teams.all %}
                <div class="btn-group btn-group-toggle align-items-center justify-content-center" style="width:27.5%;">
                    {% if week_start %}
                    <input type="radio" class="btn-check" name="{{ game.game_id }}"
                    value="{{ game.game_id }}-{{ team.team_name }}" id="{{ game.game_id }}-{{ team.team_name }}" autocomplete="off" disabled>
                    {% else %}
                    <input type="radio" class="btn-check" name="{{ game.game_id }}"
                    value="{{ game.game_id }}-{{ team.team_name }}" id="{{ game.game_id }}-{{ team.team_name }}" autocomplete="off" {% if not user_profile %}disabled{% endif %}>
                    {% endif %}
                
                    <label
                        class="btn {% if game.has_occurred and team.team_name == game.winning_team.team_name %} btn-outline-success {% else %} {% if game.has_occurred %} btn-outline-danger {% else %} btn-outline-dark {% endif %} {% endif %}"
                        for="{{ game.game_id }}-{{ team.team_name }}">
                        {% if forloop.counter == 1 %}
                        <span>{% if agent and agent == "web" %}{{ team.team_name }} {% endif %}<img src="{{ team.team_logo }}" alt="{{ team.team_name }}" height="45"></span>
                        {% else %}
                        <span><img src="{{ team.team_logo }}" alt="{{ team.team_name }}" height="45">{% if agent and agent == "web" %} {{ team.team_name }}{% endif %}</span>
                        {% endif %}
                    </label>
                </div>
                {% if forloop.counter == 1 %}
                <div style="width:10%;">
                    <p>vs.</p>
                </div>
                {% endif %}
            {% endfor %}
        </div>
        <br>
        {% endfor %}
    </div>
    {% endfor %}

    {% if user_profile %}
    <div class="row-md-3 text-center justify-content-center ">
        {% if user_profile.latest_pred_week == current_week or week_start %}
            <button type="submit" class="btn btn-outline-dark btn-lg" value="makepredictions" disabled>Locked in!</button>
        {% else %}
            <button type="submit" class="btn btn-warning btn-lg" value="makepredictions">Lock in!</button>
        {% endif %}
    </div>
    {% else %}
    <div class="row-md-3 text-center justify-content-center ">
        <p>Login before making predictions!</p>
    </div>
    {% endif %}

</form>

pickem/templates/pickem/leaderboard.html
{% extends "pickem/base.html" %}

{% block content %}
<div class="container-fluid position-relative" id="main-content">
    <h1 class="text-center mb-3">Leaderboard</h1><br>
    <div class="container">
        <!--{% if users %}
            <ul class="list-group">
                {% for curr_user_profile in users %}
                    <a href="{% url 'pickem:userhistory' curr_user_profile.user.username %}" class="list-group-item {% if curr_user_profile == user_profile %} list-group-item-info {% endif %} d-flex justify-content-between align-items-center">
                        {{ curr_user_profile.rank }} {{ curr_user_profile.user.username }}
                        <span class="badge bg-warning rounded-pill">{{ curr_user_profile.points }}</span>
                    </a>
                {% endfor %}
            </ul>
        {% else %}
            <p>Internal Error!</p>
        {% endif %}-->
        {% if users %}
        <div class="d-flex flex-wrap align-items-center justify-content-center py-2">
        <table class="table">
            <thead class="table-dark">
                <tr>
                    <th scope="col">Rank</th>
                    <th scope="col">Username</th>
                    {% if agent and agent == 'web' %}<th scope="col">Twitter</th>{% endif %}
                    <th scope="col">Points</th>
                    <th scope="col">Favorite Team</th>
                </tr>
            </thead>
            <tbody>
                {% for curr_user_profile in users %}
                <tr class="{% if curr_user_profile == user_profile %}table-info{% endif %}">
                    <th scope="row"><a href="{% url 'pickem:userhistory' curr_user_profile.user.username %}" class="nav-link link-dark">{{ curr_user_profile.rank }}</a></th>
                    <td><a href="{% url 'pickem:userhistory' curr_user_profile.user.username %}" class="nav-link link-dark">{{ curr_user_profile.user.username }}</a></td>
                    {% if agent and agent == 'web' %}<td>{% if curr_user_profile.twitter %}<a href="https://www.twitter.com/{{ curr_user_profile.twitter }}" class="nav-link link-dark">@{{ curr_user_profile.twitter }}</a>{% endif %}</td>{% endif %}
                    <td><a href="{% url 'pickem:userhistory' curr_user_profile.user.username %}" class="nav-link link-primary"><span class="badge bg-warning rounded-pill">{{ curr_user_profile.points }}</a></span></a></td>
                    <td><a href="{% url 'pickem:userhistory' curr_user_profile.user.username %}"><img src="{{ curr_user_profile.favorite_team.team_logo }}" alt="{{ curr_user_profile.favorite_team.team_name }}" height="40"></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>
        {% else %}
            <p>Internal Error!</p>
        {% endif %}
    </div>
</div>
{% endblock %}

pickem/templates/pickem/login.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'pickem/account.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pickem/login.css' %}">

    <style>
        
    </style>

    <title>OWL Pick'em</title>
</head>

<body>
    {% include 'pickem/navbar.html' %}
    <div class="container-fluid row text-center justify-content-center" id="login-body">
        <main class="form-signin">
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

            <form action="{% url 'pickem:loginaction' %}" method="post">
                {% csrf_token %}
                <h1 class="h3 mb-3 fw-normal">Login</h1>
                
                <div class="form-floating">
                    <input type="username" class="form-control" id="floatingInput" name="username" placeholder="Username" required>
                    <label for="floatingInput">Username</label>
                </div>
                <div class="form-floating">
                    <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password" required>
                    <label for="floatingPassword">Password</label>
                </div>
                <br>
                <button class="w-100 btn btn-lg btn-warning" type="submit" value="loginaction">Submit</button>
            </form>
        </div>
    </div>
</body>

pickem/templates/pickem/navbar.html
<div class="container">
    <header
        class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
        <a href="{% url 'pickem:index' %}" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
            <img class="bi me-2" src="https://owlpickem.s3.us-east-2.amazonaws.com/owl.png" alt="" width="60" height="60">
            <span class="fs-4">Pick'em</span>
        </a>

        <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
            <li><a href="{% url 'pickem:index' %}" class="nav-link px-2 {% if request.session.current_page == 'home' %}link-secondary{% else %} link-dark{% endif %}">Home</a></li>
            <li><a href="{% url 'pickem:pastweeks' %}" class="nav-link px-2 {% if request.session.current_page == 'pastweeks' %}link-secondary{% else %} link-dark{% endif %}">Past Weeks</a></li>
            <li><a href="{% url 'pickem:leaderboard' %}" class="nav-link px-2 {% if request.session.current_page == 'leaderboard' %}link-secondary{% else %} link-dark{% endif %}">Leaderboard</a></li>
            <!--<li><a href="#" class="nav-link px-2 link-dark">About</a></li>-->
        </ul>

        {% if user_profile %}
        <div class="col-md-3 text-end">
            <a href="{% url 'pickem:userhistory' user_profile.user.username %}"><button type="button" class="btn btn-outline-dark me-2">{{ user_profile.user.username }} <span class="badge bg-warning rounded-pill">{{ user_profile.points }}</span></button></a>
            <a href="{% url 'pickem:logoutaction' %}"><button type="button" class="btn btn-warning">Logout</button></a>
        </div>
        {% else %}
        <div class="col-md-3 text-end">
            <a href="{% url 'pickem:loginview' %}"><button type="button" class="btn btn-outline-dark me-2">Login</button></a>
            <a href="{% url 'pickem:signup' %}"><button type="button" class="btn btn-warning">Sign Up</button></a>
        </div>
        {% endif %}
    </header>
</div>

pickem/templates/pickem/signup.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'pickem/account.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'pickem/signup.css' %}">

    <title>OWL Pick'em</title>
</head>

<body>
    {% include 'pickem/navbar.html' %}
    <div class="container-fluid row text-center justify-content-center" id="login-body">
        <main class="form-signin">
            {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    
            <form action="{% url 'pickem:signupaction' %}" method="post">
                {% csrf_token %}
                <h1 class="h3 mb-3 fw-normal">Sign up</h1>

                <div class="form-floating">
                    <input type="email" class="form-control" id="floatingInput" name="email" placeholder="Email" required>
                    <label for="floatingInput">Email</label>
                </div>
                <div class="form-floating">
                    <input type="username" class="form-control" id="floatingInput" name="username" placeholder="Username" required>
                    <label for="floatingInput">Username</label>
                </div>
                <div class="form-floating">
                    <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password" required>
                    <label for="floatingPassword">Password</label>
                </div>
                <div class="form-floating">
                    <input type="password" class="form-control" id="floatingPassword" name="confirmpassword" placeholder="Confirm Password" required>
                    <label for="floatingPassword">Confirm Password</label>
                </div>
                <br>
                <div class="input-group mb-3">
                    <span class="input-group-text" id="twitter">@</span>
                    <input type="text" class="form-control" id="floatingInput" name="twitter" placeholder="Twitter Handle" aria-label="Username" aria-describedby="twitter">
                </div>
                <div>
                    <select class="form-select" name="team" aria-label="favorite team">
                        <option selected>No Favorite Team</option>
                        {% for team in teams %}
                        <option value="{{ team.team_name }}">{{ team.team_name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <br>
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="checkbox" name="emailupdates" id="emailupdates" checked>
                    <label class="form-check-label" for="emailupdates">
                        Send weekly reminders
                    </label>
                </div>
                <br>
                <br>
                <button class="w-100 btn btn-lg btn-warning" type="submit" value="signupaction">Submit</button>
            </form>
    </div>
</body>